all:
	@echo NoOp

eps:
	@make --no-print-directory `grep -o '^\S*\.eps' Makefile`

.PHONY: $(wildcard *.eps)

cover.eps: cover.jpg
	@convert $< $@
сурья-01.eps: сурья-01.jpg
	@convert $< $@
сурья-02-11.eps: сурья-02-11.jpg
	@convert $< $@
сурья-03-10.eps: сурья-03-10.jpg
	@convert $< $@
сурья-04-09.eps: сурья-04-09.jpg
	@convert $< $@
сурья-05.eps: сурья-05.jpg
	@convert $< $@
сурья-06.eps: сурья-06.jpg
	@convert $< $@
сурья-07.eps: сурья-07.jpg
	@convert $< $@
сурья-08.eps: сурья-08.jpg
	@convert $< $@
сурья-12.eps: сурья-12.jpg
	@convert $< $@
